version: '3'

services:
  nodejs:
    build:
      context: ./nodejs
      dockerfile: ./Dockerfile
    image: "node:api"
    ports:
      - "8080:8080"
  react:
    build:
      context: ./react
      dockerfile: ./Dockerfile
    image: "react:app"
    ports:
      - "8081:8081"
 
